### ISSUE TITLE
Bug in drawing range_axis label with spaces in name.

### ISSUE THREAD

**Issue by domik82** [gphat/chart-clicker#35]
Hi,

There is a bug when plotting a graph with range_axis label that contain spaces.

If used like that - all of the text is plotted on each other like on screen shot

![line_with_y_label_error](https://f.cloud.github.com/assets/2431071/1974369/057301a0-836e-11e3-8bdf-6ac18cd79792.png)

my $cc = Chart::Clicker->new(width => 500, height => 250);
my $defctx = $cc->get_context('default');
$defctx->range_axis->label('Time taken by Request');

Replacing space with '_' char seems to be a workaround.

![line_with_y_label](https://f.cloud.github.com/assets/2431071/1974374/1e5d662e-836e-11e3-84b0-17f985788080.png)

**Comment by gphat** [comment]
This has been fixed and will be in the upcoming Chart::Clicker 2.89 release.
