### ISSUE TITLE
Chart::Clicker fails to install because Graphics::Primitive::Driver::Cairo doesn't install

### ISSUE THREAD

**Issue by SanderP** [gphat/chart-clicker#40]
Hi,

Chart::Clicker fails to install because Cairo won't install using cpan. I tried installing Cairo by itself and as expected that fails as well:

cpan[7]> install Graphics::Primitive::Driver::Cairo
Running install for module 'Graphics::Primitive::Driver::Cairo'
Running make for G/GP/GPHAT/Graphics-Primitive-Driver-Cairo-0.46.tar.gz
  Has already been unwrapped into directory /root/.cpan/build/Graphics-Primitive-Driver-Cairo-0.46-TIFBYc
----      Unsatisfied dependencies detected during     ----
---- GPHAT/Graphics-Primitive-Driver-Cairo-0.46.tar.gz ----
    Cairo [requires]
Running make test
  Delayed until after prerequisites
Running make install
  make test had returned bad status, won't install without force
  Delayed until after prerequisites
Running install for module 'Cairo'
Running make for X/XA/XAOC/Cairo-1.104.tar.gz
  Has already been unwrapped into directory /root/.cpan/build/Cairo-1.104-LJJXSO
  No 'Makefile' created
, won't make
Running make test
  Make had some problems, won't test
Running make install
  Make had some problems, won't install
Running make for G/GP/GPHAT/Graphics-Primitive-Driver-Cairo-0.46.tar.gz
  Has already been unwrapped into directory /root/.cpan/build/Graphics-Primitive-Driver-Cairo-0.46-TIFBYc
Warning: Prerequisite 'Cairo => 0' for 'GPHAT/Graphics-Primitive-Driver-Cairo-0.46.tar.gz' failed when processing 'XAOC/Cairo-1.104.tar.gz' with 'writemakefile => NO -- No 'Makefile' created
'. Continuing, but chances to succeed are limited.
  Has already been made
Running make test
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/_.t t/author/_.t
t/author/pod.t .......... skipped: Test::Pod 1.22 required for testing POD
t/layout.t .............. Can't locate Cairo.pm in @INC (@INC contains: /root/.cpan/build/Graphics-Primitive-Driver-Cairo-0.46-TIFBYc/blib/lib /root/.cpan/build/Graphics-Primitive-Driver-Cairo-0.46-TIFBYc/blib/arch /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /root/.cpan/build/Graphics-Primitive-Driver-Cairo-0.46-TIFBYc/blib/lib/Graphics/Primitive/Driver/Cairo.pm line 8.
BEGIN failed--compilation aborted at /root/.cpan/build/Graphics-Primitive-Driver-Cairo-0.46-TIFBYc/blib/lib/Graphics/Primitive/Driver/Cairo.pm line 8.
Compilation failed in require at t/layout.t line 7.
BEGIN failed--compilation aborted at t/layout.t line 7.
t/layout.t .............. Dubious, test returned 2 (wstat 512, 0x200)
No subtests run
t/load.t ................ 1/?
# Failed test 'use Graphics::Primitive::Driver::Cairo;'
# at t/load.t line 6.
# Tried to use 'Graphics::Primitive::Driver::Cairo'.
# Error:  Can't locate Cairo.pm in @INC (@INC contains: /root/.cpan/build/Graphics-Primitive-Driver-Cairo-0.46-TIFBYc/blib/lib /root/.cpan/build/Graphics-Primitive-Driver-Cairo-0.46-TIFBYc/blib/arch /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /root/.cpan/build/Graphics-Primitive-Driver-Cairo-0.46-TIFBYc/blib/lib/Graphics/Primitive/Driver/Cairo.pm line 8.
# BEGIN failed--compilation aborted at /root/.cpan/build/Graphics-Primitive-Driver-Cairo-0.46-TIFBYc/blib/lib/Graphics/Primitive/Driver/Cairo.pm line 8.
# Compilation failed in require at (eval 4) line 2.
# BEGIN failed--compilation aborted at (eval 4) line 2.
# Looks like you failed 1 test of 1.

t/load.t ................ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
t/release-pod-syntax.t .. skipped: these tests are for release candidate testing
t/release-synopsis.t .... skipped: these tests are for release candidate testing
## Test Summary Report

t/layout.t            (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/load.t              (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=5, Tests=1,  1 wallclock secs ( 0.03 usr  0.00 sys +  0.93 cusr  0.06 csys =  1.02 CPU)
Result: FAIL
Failed 2/5 test programs. 1/1 subtests failed.
make: **\* [test_dynamic] Error 255
  GPHAT/Graphics-Primitive-Driver-Cairo-0.46.tar.gz
one dependency not OK (Cairo); additionally test harness failed
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports GPHAT/Graphics-Primitive-Driver-Cairo-0.46.tar.gz
Running make install
  make test had returned bad status, won't install without force
Failed during this command:
 GPHAT/Graphics-Primitive-Driver-Cairo-0.46.tar.gz: make_test NO one dependency not OK (Cairo); additionally test harness failed

root@qaweb:~# perl -v

This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi
(with 88 registered patches, see perl -V for more detail)
root@qaweb:~# uname -a
Linux qaweb 3.2.0-3-amd64 #1 SMP Mon Jul 23 02:45:17 UTC 2012 x86_64 GNU/Linux
root@qaweb:~#

My goal is to use Chart::Clicker to generate charts on the fly for a Perl::CGI based web site.

Fixes or workarounds appreciated!

Thanks,

```
Sander
```

**Comment by 8cold8hot** [comment]
I came across this same situation when I tried to install Devel::IPerl with Perl 5.24 on OS X 10.11, have you worked it out? Thanks.

**Comment by gphat** [comment]
The intricacies of installation of libraries like Cairo and such are rather system dependent. 😢
