### ISSUE TITLE
Warnings with recent Moose versions

### ISSUE THREAD

**Issue by epa** [gphat/chart-clicker#45]
For example

```
t/add-data.t .................... Passing a list of values to enum is deprecated. Enum values should be wrapped in an arrayref. at /usr/lib64/perl5/vendor_perl/Moose/Util/TypeConstraints.pm line 437.
        Moose::Util::TypeConstraints::enum("LineCap", "butt", "round", "square") called at /usr/share/perl5/vendor_perl/Graphics/Primitive/Brush.pm line 9
        require Graphics/Primitive/Brush.pm called at /usr/share/perl5/vendor_perl/Graphics/Primitive/Border.pm line 9
        Graphics::Primitive::Border::BEGIN() called at /usr/share/perl5/vendor_perl/Graphics/Primitive/Brush.pm line 0
        eval {...} called at /usr/share/perl5/vendor_perl/Graphics/Primitive/Brush.pm line 0
        require Graphics/Primitive/Border.pm called at /home/eda/git_working/fedora-packages/SOURCES/perl-Chart-Clicker/Chart-Clicker-2.88/blib/lib/Chart/Clicker.pm line 14
        Chart::Clicker::BEGIN() called at /usr/share/perl5/vendor_perl/Graphics/Primitive/Brush.pm line 0
        eval {...} called at /usr/share/perl5/vendor_perl/Graphics/Primitive/Brush.pm line 0
        require Chart/Clicker.pm called at t/add-data.t line 4
        main::BEGIN() called at /usr/share/perl5/vendor_perl/Graphics/Primitive/Brush.pm line 0
        eval {...} called at /usr/share/perl5/vendor_perl/Graphics/Primitive/Brush.pm line 0
```

**Comment by dionys** [comment]
These warnings from `Graphics::Primitive`. And they fixed with gphat/graphics-primitive@88a69312763aa7aead5ad42c174af57c3a7f31e8 commit.

Issue can be closed. Or needs to change dependency to `Graphics::Primitive 0.62`.

**Comment by epa** [comment]
Thanks.  I think bumping the dependency will be best.

**Comment by johnrb68** [comment]
Is this still an issue, or is there something new going on?

I seem to be getting same error message:

`Passing a list of values to enum is deprecated. Enum values should be wrapped in an arrayref. at /usr/lib/x86_64-linux-gnu/perl5/5.22/Moose/Util/TypeConstraints.pm line 437.
        Moose::Util::TypeConstraints::enum("Layout::Manager::Flow::Anchors", "north", "south", "east", "west") called at /usr/share/perl5/Layout/Manager/Flow.pm line 8
        require Layout/Manager/Flow.pm called at /usr/share/perl5/Chart/Clicker/Decoration/Legend.pm line 14
        Chart::Clicker::Decoration::Legend::BEGIN() called at /usr/share/perl5/Layout/Manager/Flow.pm line 0
        eval {...} called at /usr/share/perl5/Layout/Manager/Flow.pm line 0
        require Chart/Clicker/Decoration/Legend.pm called at /usr/share/perl5/Chart/Clicker.pm line 22
        Chart::Clicker::BEGIN() called at /usr/share/perl5/Layout/Manager/Flow.pm line 0
        eval {...} called at /usr/share/perl5/Layout/Manager/Flow.pm line 0
        require Chart/Clicker.pm called at /home/oxygen/chartimage.pl line 6
        main::BEGIN() called at /usr/share/perl5/Layout/Manager/Flow.pm line 0
        eval {...} called at /usr/share/perl5/Layout/Manager/Flow.pm line 0
`

I just moved long running code from Ubuntu 14.04 LTS to new 16.04 LTS server build, and now I get that message, where I didn't on the older server.

Right now I am piping output to log file, as the script using Chart Clicker runs every hour, and emails from cron with that message were getting annoying.

Chart clicker was installed using:
apt-get install libchart-clicker-perl

New Ubuntu release and new build, everything should be up to date.

So not sure if this is same issue or something new.

**Comment by gphat** [comment]
Most recent release should fix this, assuming it's packaged to wherever you're getting it.
